mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password)
}

mutation createProduct($data: ProductInput) {
  createProduct(data: $data)
}

mutation updateProduct($updateProductId: Int!, $data: ProductInput) {
  updateProduct(id: $updateProductId, data: $data)
}

mutation updateCategory(
  $updateCategoryId: Int!
  $data: CategoryInput
  $isActive: Boolean
) {
  updateCategory(id: $updateCategoryId, data: $data, isActive: $isActive)
}

mutation createCategory($data: CategoryInput) {
  createCategory(data: $data)
}

mutation createOrder($data: OrderInput) {
  createOrder(data: $data)
}
