query me {
  me {
    id
    display
    contact
    gender
    role {
      id
      name
    }
    createdDate
  }
}

query ProductList(
  $offset: Int
  $limit: Int
  $code: String
  $filter: FilterProduct
) {
  productList(offset: $offset, limit: $limit, code: $code, filter: $filter) {
    id
    title
    description
    type
    category {
      id
      name
      root
    }
    sku {
      id
      name
      price
      discount
      unit
    }
    code
    images
    addons {
      value
      name
      isRequired
      id
    }
  }
}

query product($productId: Int!) {
  product(id: $productId) {
    id
    title
    description
    type
    stockAlter
    category {
      id
      name
      root
    }
    sku {
      id
      name
      price
      discount
      unit
    }
    code
    images
    integrates {
      qty
      product {
        title
        images
        id
      }
      integrate {
        id
        images
        title
      }
      id
    }
    addons {
      value
      name
      isRequired
      id
    }
  }
}

query categoryList {
  categoryList
}

query category($categoryId: Int!) {
  category(id: $categoryId) {
    id
    name
    root
  }
}

query orderList($offset: Int, $limit: Int) {
  orderList(offset: $offset, limit: $limit) {
    uuid
    total
    status
    set
    paid
    name
    items {
      id
      qty
      price
      sku {
        id
        name
        discount
        price
        unit
      }
      status
      discount
    }
    id
    address
  }
}

query order($token: String, $orderId: Int) {
  order(token: $token, id: $orderId) {
    uuid
    total
    status
    set
    paid
    name
    items {
      id
      qty
      sku {
        price
        discount
        id
        unit
        name
      }
      product {
        title
        images
        code
        description
        id
      }
      price
      discount
      status
      addons
      remark
    }
    id
    address
  }
}

query generateTokenOrder($set: Int!) {
  generateTokenOrder(set: $set)
}
