query me {
  me {
    id
    display
    contact
    gender
    role {
      id
      name
    }
    createdDate
  }
}

query ProductList(
  $offset: Int
  $limit: Int
  $code: String
  $filter: FilterProduct
) {
  productList(offset: $offset, limit: $limit, code: $code, filter: $filter) {
    id
    title
    description
    type
    category {
      id
      name
      root
    }
    sku {
      id
      name
      price
      discount
      unit
    }
    code
    images
    addons {
      value
      name
      isRequired
      id
    }
  }
}

query product($productId: Int!) {
  product(id: $productId) {
    id
    title
    description
    type
    stockAlter
    category {
      id
      name
      root
    }
    sku {
      id
      name
      price
      discount
      unit
    }
    code
    images
    integrates {
      qty
      product {
        title
        images
        id
      }
      integrate {
        id
        images
        title
      }
      id
    }
    addons {
      value
      name
      isRequired
      id
    }
  }
}

query categoryList {
  categoryList
}

query category($categoryId: Int!) {
  category(id: $categoryId) {
    id
    name
    root
  }
}

query orderList(
  $offset: Int
  $limit: Int
  $viewBy: OrderViewBy
  $status: [StatusOrder]
  $orderId: String
) {
  orderList(
    offset: $offset
    limit: $limit
    viewBy: $viewBy
    status: $status
    orderId: $orderId
  ) {
    id
    items {
      id
      price
      product {
        id
        images
        title
        code
      }
      qty
      discount
      addons
      remark
      sku {
        name
      }
      status
    }
    status
    name
    paid
    set
    total
    uuid
    note
    log {
      date
      text
      by {
        id
        display
      }
    }
  }
}

query order($token: String, $orderId: Int) {
  order(token: $token, id: $orderId) {
    id
    address
    status
    name
    paid
    set
    total
    uuid
    note
    log {
      date
      text
      by {
        id
        display
      }
    }
    items {
      id
      qty
      sku {
        price
        discount
        id
        unit
        name
      }
      product {
        title
        images
        code
        description
        id
      }
      price
      discount
      status
      addons
      remark
    }
  }
}
